### ISSUE TITLE
Add Readme.md file

### ISSUE THREAD

**Issue by yogeshAgarwal** [hasnarobert/vowelrecognition#1]
In this there is no details of your code and other program so please add this file

**Comment by hasnarobert** [comment]
This was my bachelors diploma project and I just stored it here so I don't lose it.
If you want to run it, just do a `ant run` and a Java Swing UI should pop up.

**Comment by hasnarobert** [comment]
I liked that someone actually ended up here and spent the time to create the issue, so I created the README file. I doubt this will be useful to you, but in case it is and you need help with this I am happy to assist.

**Comment by yogeshAgarwal** [comment]
Thanku Very much, it will help me alot 👍
